version: '3.8'

services:
  propellant_minio:
    image: minio/minio:latest
    container_name: propellant_minio
    restart: always
    environment:
      MINIO_ROOT_USER: propellant_admin
      MINIO_ROOT_PASSWORD: propellant_secret_pass
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - propellant_minio_data:/data

  propellant_postgres:
    image: postgres:16-alpine
    container_name: propellant_postgres
    restart: always
    environment:
      POSTGRES_USER: propellant_user
      POSTGRES_PASSWORD: propellant_pass
      POSTGRES_DB: propellant_db
    ports:
      - "5433:5432"
    volumes:
      - propellant_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql

  propellant_adminer:
    image: adminer:latest
    container_name: propellant_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - propellant_postgres

volumes:
  propellant_minio_data:
  propellant_pg_data: